name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build and Test
      run: ./gradlew --info test
#      with:
#         aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
#         aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
#         aws-region: ap-northeast-2

     # Test Result
    - name: Report Unit Test Result
      uses: dorny/test-reporter@v1
      if: always()  # success() || failure()
      with:
       name: Test Result
       path: target/reports/*.xml
       reporter: java-junit
       fail-on-error: true
